//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DivinityModManager.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DivinityModManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When the game launches through the mod manager, this action will be performed 的本地化字符串。
        /// </summary>
        public static string ActionOnGameLaunchTooltip {
            get {
                return ResourceManager.GetString("ActionOnGameLaunchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active Mods 的本地化字符串。
        /// </summary>
        public static string ActiveMods {
            get {
                return ResourceManager.GetString("ActiveMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active Mods 的本地化字符串。
        /// </summary>
        public static string ActiveMods1 {
            get {
                return ResourceManager.GetString("ActiveMods1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter Active Mods 的本地化字符串。
        /// </summary>
        public static string ActiveModsTooltip {
            get {
                return ResourceManager.GetString("ActiveModsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New Order 的本地化字符串。
        /// </summary>
        public static string Add_New_Order {
            get {
                return ResourceManager.GetString("Add New Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New Load Order 的本地化字符串。
        /// </summary>
        public static string AddNewOrderButtonTooltip {
            get {
                return ResourceManager.GetString("AddNewOrderButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced 的本地化字符串。
        /// </summary>
        public static string AdvancedSettingsHeader {
            get {
                return ResourceManager.GetString("AdvancedSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adventure 的本地化字符串。
        /// </summary>
        public static string Adventure {
            get {
                return ResourceManager.GetString("Adventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always Disable Telemetry 的本地化字符串。
        /// </summary>
        public static string Always_Disable_Telemetry {
            get {
                return ResourceManager.GetString("Always Disable Telemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author 的本地化字符串。
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created by 的本地化字符串。
        /// </summary>
        public static string AuthorTip {
            get {
                return ResourceManager.GetString("AuthorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Add Missing Dependencies When Exporting 的本地化字符串。
        /// </summary>
        public static string Auto_Add_Missing_Dependencies_When_Exporting {
            get {
                return ResourceManager.GetString("Auto Add Missing Dependencies When Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically add dependency mods above their dependents in the exported load order, if omitted from the active order 的本地化字符串。
        /// </summary>
        public static string Automatically_add_dependency_mods_above_their_dependents_in_the_exported_load_order__if_omitted_from_the_active_order {
            get {
                return ResourceManager.GetString("Automatically add dependency mods above their dependents in the exported load ord" +
                        "er, if omitted from the active order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically check for updates when the program starts 的本地化字符串。
        /// </summary>
        public static string Automatically_check_for_updates_when_the_program_starts {
            get {
                return ResourceManager.GetString("Automatically check for updates when the program starts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Campaign 的本地化字符串。
        /// </summary>
        public static string Campaign {
            get {
                return ResourceManager.GetString("Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changelog 的本地化字符串。
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for Updates 的本地化字符串。
        /// </summary>
        public static string Check_for_Updates {
            get {
                return ResourceManager.GetString("Check for Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Classic) 的本地化字符串。
        /// </summary>
        public static string ClassicMod {
            get {
                return ResourceManager.GetString("ClassicMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Workshop Cache 的本地化字符串。
        /// </summary>
        public static string ClearCacheText {
            get {
                return ResourceManager.GetString("ClearCacheText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete the local workshop cache used for tag display, located at Data\workshopdata.json 的本地化字符串。
        /// </summary>
        public static string ClearCacheTextTooltip {
            get {
                return ResourceManager.GetString("ClearCacheTextTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Keybinding 的本地化字符串。
        /// </summary>
        public static string ClearHotkeyMenuItemHeader {
            get {
                return ResourceManager.GetString("ClearHotkeyMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove All Missing 的本地化字符串。
        /// </summary>
        public static string ClearMissingModsButton {
            get {
                return ResourceManager.GetString("ClearMissingModsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove all missing mods from the load order. 的本地化字符串。
        /// </summary>
        public static string ClearMissingModsButtonTooltip {
            get {
                return ResourceManager.GetString("ClearMissingModsButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Cache 的本地化字符串。
        /// </summary>
        public static string ClearWorkshopCache {
            get {
                return ResourceManager.GetString("ClearWorkshopCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command 的本地化字符串。
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Mod Path to Clipboard 的本地化字符串。
        /// </summary>
        public static string CopyModPathToClipboardHeader {
            get {
                return ResourceManager.GetString("CopyModPathToClipboardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Order to Clipboard 的本地化字符串。
        /// </summary>
        public static string CopyOrderToClipboardHeader {
            get {
                return ResourceManager.GetString("CopyOrderToClipboardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Path to Clipboard 的本地化字符串。
        /// </summary>
        public static string CopyPathToClipboardHeader {
            get {
                return ResourceManager.GetString("CopyPathToClipboardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Selected to Mods Folder 的本地化字符串。
        /// </summary>
        public static string CopySelectedModsButton {
            get {
                return ResourceManager.GetString("CopySelectedModsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy FolderName to Clipboard 的本地化字符串。
        /// </summary>
        public static string CopyToClipboardFolderNameHeader {
            get {
                return ResourceManager.GetString("CopyToClipboardFolderNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy to Clipboard 的本地化字符串。
        /// </summary>
        public static string CopyToClipboardTooltip {
            get {
                return ResourceManager.GetString("CopyToClipboardTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy UUID to Clipboard 的本地化字符串。
        /// </summary>
        public static string CopyToClipboardUUIDHeader {
            get {
                return ResourceManager.GetString("CopyToClipboardUUIDHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current 的本地化字符串。
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current 的本地化字符串。
        /// </summary>
        public static string CurrentHeader {
            get {
                return ResourceManager.GetString("CurrentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Definitive Edition) 的本地化字符串。
        /// </summary>
        public static string DefinitiveEditionMod {
            get {
                return ResourceManager.GetString("DefinitiveEditionMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Selected Mods... 的本地化字符串。
        /// </summary>
        public static string Delete_Selected_Mods___ {
            get {
                return ResourceManager.GetString("Delete Selected Mods...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Mod... 的本地化字符串。
        /// </summary>
        public static string DeleteModHeader {
            get {
                return ResourceManager.GetString("DeleteModHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete files permanently, instead of moving them to the Reycling Bin. 的本地化字符串。
        /// </summary>
        public static string DeletionOptionCheckboxTooltip {
            get {
                return ResourceManager.GetString("DeletionOptionCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dependencies: 的本地化字符串。
        /// </summary>
        public static string DependenciesTip {
            get {
                return ResourceManager.GetString("DependenciesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Missing Mod Warnings 的本地化字符串。
        /// </summary>
        public static string Disable_Missing_Mod_Warnings {
            get {
                return ResourceManager.GetString("Disable Missing Mod Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate a Coffee... 的本地化字符串。
        /// </summary>
        public static string Donate_a_Coffee___ {
            get {
                return ResourceManager.GetString("Donate a Coffee...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate a Coffee 的本地化字符串。
        /// </summary>
        public static string DonateACoffee {
            get {
                return ResourceManager.GetString("DonateACoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download &amp; Install the Script Extender... 的本地化字符串。
        /// </summary>
        public static string Download___Install_the_Script_Extender___ {
            get {
                return ResourceManager.GetString("Download & Install the Script Extender...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Update 的本地化字符串。
        /// </summary>
        public static string DownloadUpdate {
            get {
                return ResourceManager.GetString("DownloadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Automatic Updates 的本地化字符串。
        /// </summary>
        public static string Enable_Automatic_Updates {
            get {
                return ResourceManager.GetString("Enable Automatic Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Developer Mode 的本地化字符串。
        /// </summary>
        public static string Enable_Developer_Mode {
            get {
                return ResourceManager.GetString("Enable Developer Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable DirectX 11 Mode 的本地化字符串。
        /// </summary>
        public static string Enable_DirectX_11_Mode {
            get {
                return ResourceManager.GetString("Enable DirectX 11 Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Story Log 的本地化字符串。
        /// </summary>
        public static string Enable_Story_Log {
            get {
                return ResourceManager.GetString("Enable Story Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable DirectX 11 Mode 的本地化字符串。
        /// </summary>
        public static string EnableDirectX11Mode {
            get {
                return ResourceManager.GetString("EnableDirectX11Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, when launching the game, bg3_dx11.exe is used instead. 的本地化字符串。
        /// </summary>
        public static string EnableDirectX11ModeTooltip {
            get {
                return ResourceManager.GetString("EnableDirectX11ModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Example: Baldur&apos;s Gate 3/Data 的本地化字符串。
        /// </summary>
        public static string Example__Baldur_s_Gate_3_Data {
            get {
                return ResourceManager.GetString("Example: Baldur\'s Gate 3/Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Order to Archive (.zip) 的本地化字符串。
        /// </summary>
        public static string Export_Order_to_Archive___zip_ {
            get {
                return ResourceManager.GetString("Export Order to Archive (.zip)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Order to Archive As... 的本地化字符串。
        /// </summary>
        public static string Export_Order_to_Archive_As___ {
            get {
                return ResourceManager.GetString("Export Order to Archive As...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Order to Game 的本地化字符串。
        /// </summary>
        public static string Export_Order_to_Game {
            get {
                return ResourceManager.GetString("Export Order to Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Order to Text File... 的本地化字符串。
        /// </summary>
        public static string Export_Order_to_Text_File___ {
            get {
                return ResourceManager.GetString("Export Order to Text File...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Order As List... 的本地化字符串。
        /// </summary>
        public static string ExportOrderAsListHeader {
            get {
                return ResourceManager.GetString("ExportOrderAsListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Active Mods to Zip As... 的本地化字符串。
        /// </summary>
        public static string ExportOrderToArchiveAsTooltip {
            get {
                return ResourceManager.GetString("ExportOrderToArchiveAsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Active Mods to Zip 的本地化字符串。
        /// </summary>
        public static string ExportOrderToArchiveTooltip {
            get {
                return ResourceManager.GetString("ExportOrderToArchiveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Order to Game 的本地化字符串。
        /// </summary>
        public static string ExportToModSettingsButtonTooltip {
            get {
                return ResourceManager.GetString("ExportToModSettingsButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract Active Adventure Mod To... 的本地化字符串。
        /// </summary>
        public static string Extract_Active_Adventure_Mod_To___ {
            get {
                return ResourceManager.GetString("Extract Active Adventure Mod To...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract Selected Mods To... 的本地化字符串。
        /// </summary>
        public static string Extract_Selected_Mods_To___ {
            get {
                return ResourceManager.GetString("Extract Selected Mods To...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Files to Delete 的本地化字符串。
        /// </summary>
        public static string FilesToDelete {
            get {
                return ResourceManager.GetString("FilesToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus Active Mods List 的本地化字符串。
        /// </summary>
        public static string Focus_Active_Mods_List {
            get {
                return ResourceManager.GetString("Focus Active Mods List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus Inactive Mods List 的本地化字符串。
        /// </summary>
        public static string Focus_Inactive_Mods_List {
            get {
                return ResourceManager.GetString("Focus Inactive Mods List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Data Path 的本地化字符串。
        /// </summary>
        public static string Game_Data_Path {
            get {
                return ResourceManager.GetString("Game Data Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Executable Path 的本地化字符串。
        /// </summary>
        public static string Game_Executable_Path {
            get {
                return ResourceManager.GetString("Game Executable Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When the game launches through the mod manager, this action will be performed 的本地化字符串。
        /// </summary>
        public static string GameLaunchActionComboBoxTooltip {
            get {
                return ResourceManager.GetString("GameLaunchActionComboBoxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Launch Params 的本地化字符串。
        /// </summary>
        public static string GameLaunchParams {
            get {
                return ResourceManager.GetString("GameLaunchParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string GameLaunchParamsClearHeader {
            get {
                return ResourceManager.GetString("GameLaunchParamsClearHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear current params 的本地化字符串。
        /// </summary>
        public static string GameLaunchParamsClearTooltip {
            get {
                return ResourceManager.GetString("GameLaunchParamsClearTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically load the last save when loading into the main menu 的本地化字符串。
        /// </summary>
        public static string GameLaunchParamsContinueGame {
            get {
                return ResourceManager.GetString("GameLaunchParamsContinueGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Limit the cpu to x amount of threads (unknown if this works) 的本地化字符串。
        /// </summary>
        public static string GameLaunchParamsCpuLimit {
            get {
                return ResourceManager.GetString("GameLaunchParamsCpuLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A directory to write story logs to 的本地化字符串。
        /// </summary>
        public static string GameLaunchParamsLogPath {
            get {
                return ResourceManager.GetString("GameLaunchParamsLogPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enables the story log 的本地化字符串。
        /// </summary>
        public static string GameLaunchParamsStoryLog {
            get {
                return ResourceManager.GetString("GameLaunchParamsStoryLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameters to pass to the game executable when launching the game through the mod manager 的本地化字符串。
        /// </summary>
        public static string GameLaunchParamsTooltip {
            get {
                return ResourceManager.GetString("GameLaunchParamsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purpose unknown. 的本地化字符串。
        /// </summary>
        public static string GameLaunchParamsUnknown {
            get {
                return ResourceManager.GetString("GameLaunchParamsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GM Campaign 的本地化字符串。
        /// </summary>
        public static string GMCampaign {
            get {
                return ResourceManager.GetString("GMCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go 的本地化字符串。
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to Other List 的本地化字符串。
        /// </summary>
        public static string Go_to_Other_List {
            get {
                return ResourceManager.GetString("Go to Other List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home Page: 的本地化字符串。
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If a load order is missing mods, no warnings will be displayed 的本地化字符串。
        /// </summary>
        public static string If_a_load_order_is_missing_mods__no_warnings_will_be_displayed {
            get {
                return ResourceManager.GetString("If a load order is missing mods, no warnings will be displayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, Larian&apos;s telemetry options for BG3 will always be disabled, regardless of active mods. Telemetry is always disabled if mods are active 的本地化字符串。
        /// </summary>
        public static string If_enabled__Larian_s_telemetry_options_for_BG3_will_always_be_disabled__regardless_of_active_mods__Telemetry_is_always_disabled_if_mods_are_active {
            get {
                return ResourceManager.GetString("If enabled, Larian\'s telemetry options for BG3 will always be disabled, regardles" +
                        "s of active mods. Telemetry is always disabled if mods are active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, when launching the game, bg3_dx11.exe is used instead 的本地化字符串。
        /// </summary>
        public static string If_enabled__when_launching_the_game__bg3_dx11_exe_is_used_instead {
            get {
                return ResourceManager.GetString("If enabled, when launching the game, bg3_dx11.exe is used instead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Mod... 的本地化字符串。
        /// </summary>
        public static string Import_Mod___ {
            get {
                return ResourceManager.GetString("Import Mod...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Order from Archive... 的本地化字符串。
        /// </summary>
        public static string Import_Order_from_Archive___ {
            get {
                return ResourceManager.GetString("Import Order from Archive...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Order from File... 的本地化字符串。
        /// </summary>
        public static string Import_Order_from_File___ {
            get {
                return ResourceManager.GetString("Import Order from File...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Order from Save... 的本地化字符串。
        /// </summary>
        public static string Import_Order_from_Save___ {
            get {
                return ResourceManager.GetString("Import Order from Save...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Order from Save As New Order... 的本地化字符串。
        /// </summary>
        public static string Import_Order_from_Save_As_New_Order___ {
            get {
                return ResourceManager.GetString("Import Order from Save As New Order...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inactive Mods 的本地化字符串。
        /// </summary>
        public static string InactiveMods {
            get {
                return ResourceManager.GetString("InactiveMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter Inactive Mods 的本地化字符串。
        /// </summary>
        public static string InactiveModsTooltip {
            get {
                return ResourceManager.GetString("InactiveModsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The mod order index column 的本地化字符串。
        /// </summary>
        public static string IndexHelpText {
            get {
                return ResourceManager.GetString("IndexHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keybinding 的本地化字符串。
        /// </summary>
        public static string Keybinding {
            get {
                return ResourceManager.GetString("Keybinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyboard Shortcuts 的本地化字符串。
        /// </summary>
        public static string KeybindingsTabHeader {
            get {
                return ResourceManager.GetString("KeybindingsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Updated 的本地化字符串。
        /// </summary>
        public static string LastUpdatedHeader {
            get {
                return ResourceManager.GetString("LastUpdatedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Updated on 的本地化字符串。
        /// </summary>
        public static string LastUpdatedOn {
            get {
                return ResourceManager.GetString("LastUpdatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch Game 的本地化字符串。
        /// </summary>
        public static string Launch_Game {
            get {
                return ResourceManager.GetString("Launch Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License 的本地化字符串。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Order From Selected GM Campaign 的本地化字符串。
        /// </summary>
        public static string Load_Order_From_Selected_GM_Campaign {
            get {
                return ResourceManager.GetString("Load Order From Selected GM Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Mod Manager Logs 的本地化字符串。
        /// </summary>
        public static string LogEnabledCheckbox {
            get {
                return ResourceManager.GetString("LogEnabledCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically save logs to _Logs 的本地化字符串。
        /// </summary>
        public static string LogEnabledCheckboxTooltip {
            get {
                return ResourceManager.GetString("LogEnabledCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modes 的本地化字符串。
        /// </summary>
        public static string Modes {
            get {
                return ResourceManager.GetString("Modes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modes 的本地化字符串。
        /// </summary>
        public static string ModesHeader {
            get {
                return ResourceManager.GetString("ModesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modified Date 的本地化字符串。
        /// </summary>
        public static string ModifiedDateHeader {
            get {
                return ResourceManager.GetString("ModifiedDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Order 的本地化字符串。
        /// </summary>
        public static string ModOrder {
            get {
                return ResourceManager.GetString("ModOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Updates 的本地化字符串。
        /// </summary>
        public static string ModUpdates {
            get {
                return ResourceManager.GetString("ModUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move to Bottom of Active List 的本地化字符串。
        /// </summary>
        public static string Move_to_Bottom_of_Active_List {
            get {
                return ResourceManager.GetString("Move to Bottom of Active List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move to Top of Active List 的本地化字符串。
        /// </summary>
        public static string Move_to_Top_of_Active_List {
            get {
                return ResourceManager.GetString("Move to Top of Active List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moved Selected Mods to Opposite List 的本地化字符串。
        /// </summary>
        public static string Moved_Selected_Mods_to_Opposite_List {
            get {
                return ResourceManager.GetString("Moved Selected Mods to Opposite List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string NewHeader {
            get {
                return ResourceManager.GetString("NewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Mods 的本地化字符串。
        /// </summary>
        public static string NewMods {
            get {
                return ResourceManager.GetString("NewMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On Game Launch 的本地化字符串。
        /// </summary>
        public static string OnGameLaunch {
            get {
                return ResourceManager.GetString("OnGameLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Extender Logs Folder 的本地化字符串。
        /// </summary>
        public static string Open_Extender_Logs_Folder {
            get {
                return ResourceManager.GetString("Open Extender Logs Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Game Folder 的本地化字符串。
        /// </summary>
        public static string Open_Game_Folder {
            get {
                return ResourceManager.GetString("Open Game Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Keyboard Shortcuts 的本地化字符串。
        /// </summary>
        public static string Open_Keyboard_Shortcuts {
            get {
                return ResourceManager.GetString("Open Keyboard Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Mods Folder 的本地化字符串。
        /// </summary>
        public static string Open_Mods_Folder {
            get {
                return ResourceManager.GetString("Open Mods Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Preferences 的本地化字符串。
        /// </summary>
        public static string Open_Preferences {
            get {
                return ResourceManager.GetString("Open Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Repository Page... 的本地化字符串。
        /// </summary>
        public static string Open_Repository_Page___ {
            get {
                return ResourceManager.GetString("Open Repository Page...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Workshop Folder 的本地化字符串。
        /// </summary>
        public static string Open_Workshop_Folder {
            get {
                return ResourceManager.GetString("Open Workshop Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Adventure Mod in File Explorer... 的本地化字符串。
        /// </summary>
        public static string OpenAdventureModInFileExplorerHeader {
            get {
                return ResourceManager.GetString("OpenAdventureModInFileExplorerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate a Coffee to the Developer (LaughingLeader) 的本地化字符串。
        /// </summary>
        public static string OpenDonationPageButtonTooltip {
            get {
                return ResourceManager.GetString("OpenDonationPageButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Exported Mod Order File... 的本地化字符串。
        /// </summary>
        public static string OpenExportedModOrderFileHeader {
            get {
                return ResourceManager.GetString("OpenExportedModOrderFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Logs Folder 的本地化字符串。
        /// </summary>
        public static string OpenExtenderLogsFolderButtonTooltip {
            get {
                return ResourceManager.GetString("OpenExtenderLogsFolderButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch Game 的本地化字符串。
        /// </summary>
        public static string OpenGameButtonTooltip {
            get {
                return ResourceManager.GetString("OpenGameButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Game Folder... 的本地化字符串。
        /// </summary>
        public static string OpenGameFolderInFileExplorerHeader {
            get {
                return ResourceManager.GetString("OpenGameFolderInFileExplorerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open in File Explorer... 的本地化字符串。
        /// </summary>
        public static string OpenModSettingsInFileExplorerHeader {
            get {
                return ResourceManager.GetString("OpenModSettingsInFileExplorerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Mods Folder 的本地化字符串。
        /// </summary>
        public static string OpenModsFolderButtonTooltip {
            get {
                return ResourceManager.GetString("OpenModsFolderButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Project Page (Github) 的本地化字符串。
        /// </summary>
        public static string OpenRepoPageButtonTooltip {
            get {
                return ResourceManager.GetString("OpenRepoPageButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Settings Folder 的本地化字符串。
        /// </summary>
        public static string OpenSettingsFolderTooltip {
            get {
                return ResourceManager.GetString("OpenSettingsFolderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Workshop Folder 的本地化字符串。
        /// </summary>
        public static string OpenWorkshopFolderButtonTooltip {
            get {
                return ResourceManager.GetString("OpenWorkshopFolderButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Steam Workshop Page (Browser)... 的本地化字符串。
        /// </summary>
        public static string OpenWorkshopPageHeader {
            get {
                return ResourceManager.GetString("OpenWorkshopPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Steam Workshop Page (Steam)... 的本地化字符串。
        /// </summary>
        public static string OpenWorkshopPageInSteamHeader {
            get {
                return ResourceManager.GetString("OpenWorkshopPageInSteamHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overrides 的本地化字符串。
        /// </summary>
        public static string Overrides {
            get {
                return ResourceManager.GetString("Overrides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This mod overrides base game files directly.					As long as this mod exists in the Mods folder,				these files will be overwritten, even if the mod is disabled. 的本地化字符串。
        /// </summary>
        public static string OverrideWarning {
            get {
                return ResourceManager.GetString("OverrideWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If this is intended, you can ignore this warning. 的本地化字符串。
        /// </summary>
        public static string OverrideWarning2 {
            get {
                return ResourceManager.GetString("OverrideWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This mod can be rearranged in the load order, due to it also having files of its own. Note that disabling it will not disable the file overrides. 的本地化字符串。
        /// </summary>
        public static string OverrideWarning3 {
            get {
                return ResourceManager.GetString("OverrideWarning3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overwritten builtin folders: 的本地化字符串。
        /// </summary>
        public static string OverwrittenFolders {
            get {
                return ResourceManager.GetString("OverwrittenFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permanent 的本地化字符串。
        /// </summary>
        public static string Permanent {
            get {
                return ResourceManager.GetString("Permanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preferences 的本地化字符串。
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Profile 的本地化字符串。
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh Workshop Updates 的本地化字符串。
        /// </summary>
        public static string Refresh_Workshop_Updates {
            get {
                return ResourceManager.GetString("Refresh Workshop Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh Mods and Workshop Updates 的本地化字符串。
        /// </summary>
        public static string RefreshButtonTooltip {
            get {
                return ResourceManager.GetString("RefreshButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload All 的本地化字符串。
        /// </summary>
        public static string Reload_All {
            get {
                return ResourceManager.GetString("Reload All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove from Load Order 的本地化字符串。
        /// </summary>
        public static string RemoveFromLoadOrderCheckboxContent {
            get {
                return ResourceManager.GetString("RemoveFromLoadOrderCheckboxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove deleted mods from the active load order. 的本地化字符串。
        /// </summary>
        public static string RemoveFromLoadOrderCheckboxTooltip {
            get {
                return ResourceManager.GetString("RemoveFromLoadOrderCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report an Issue 的本地化字符串。
        /// </summary>
        public static string ReportAnIssue {
            get {
                return ResourceManager.GetString("ReportAnIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset extender settings to their default values 的本地化字符串。
        /// </summary>
        public static string ResetExtenderSettingsToDefaultTooltip {
            get {
                return ResourceManager.GetString("ResetExtenderSettingsToDefaultTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Keybinding 的本地化字符串。
        /// </summary>
        public static string ResetHotkeyMenuItemHeader {
            get {
                return ResourceManager.GetString("ResetHotkeyMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset to Default 的本地化字符串。
        /// </summary>
        public static string ResetKeybindings {
            get {
                return ResourceManager.GetString("ResetKeybindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset all keybindings to their default value 的本地化字符串。
        /// </summary>
        public static string ResetKeybindingsTooltip {
            get {
                return ResourceManager.GetString("ResetKeybindingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save and restore the window location when the application starts. 的本地化字符串。
        /// </summary>
        public static string Save_and_restore_the_window_location_when_the_application_starts_ {
            get {
                return ResourceManager.GetString("Save and restore the window location when the application starts.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Order 的本地化字符串。
        /// </summary>
        public static string Save_Order {
            get {
                return ResourceManager.GetString("Save Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Order As... 的本地化字符串。
        /// </summary>
        public static string Save_Order_As___ {
            get {
                return ResourceManager.GetString("Save Order As...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Window Location 的本地化字符串。
        /// </summary>
        public static string Save_Window_Location {
            get {
                return ResourceManager.GetString("Save Window Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Order As... 的本地化字符串。
        /// </summary>
        public static string SaveAsButtonTooltip {
            get {
                return ResourceManager.GetString("SaveAsButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Load Order to File 的本地化字符串。
        /// </summary>
        public static string SaveButtonTooltip {
            get {
                return ResourceManager.GetString("SaveButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saved Load Orders Path 的本地化字符串。
        /// </summary>
        public static string Saved_Load_Orders_Path {
            get {
                return ResourceManager.GetString("Saved Load Orders Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string SaveSettingsButton {
            get {
                return ResourceManager.GetString("SaveSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Settings (CTRL + S) 的本地化字符串。
        /// </summary>
        public static string SaveSettingsTooltip {
            get {
                return ResourceManager.GetString("SaveSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script Extender 的本地化字符串。
        /// </summary>
        public static string ScriptExtender {
            get {
                return ResourceManager.GetString("ScriptExtender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the path to the Baldur&apos;s Gate 3 root installation folder 的本地化字符串。
        /// </summary>
        public static string SetRootInstallationFolderWindowTitle {
            get {
                return ResourceManager.GetString("SetRootInstallationFolderWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shift Focus on Swap 的本地化字符串。
        /// </summary>
        public static string Shift_Focus_on_Swap {
            get {
                return ResourceManager.GetString("Shift Focus on Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shortcuts 的本地化字符串。
        /// </summary>
        public static string Shortcuts {
            get {
                return ResourceManager.GetString("Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Display Names for Mods 的本地化字符串。
        /// </summary>
        public static string Show_Display_Names_for_Mods {
            get {
                return ResourceManager.GetString("Show Display Names for Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show File Names for Mods 的本地化字符串。
        /// </summary>
        public static string Show_File_Names_for_Mods {
            get {
                return ResourceManager.GetString("Show File Names for Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show File Name 的本地化字符串。
        /// </summary>
        public static string ShowFileName {
            get {
                return ResourceManager.GetString("ShowFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Mod Display Name 的本地化字符串。
        /// </summary>
        public static string ShowModDisplayName {
            get {
                return ResourceManager.GetString("ShowModDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip 的本地化字符串。
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pass the --skip-launcher args when launching the game 的本地化字符串。
        /// </summary>
        public static string Skip_Launcher {
            get {
                return ResourceManager.GetString("Skip Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip Update 的本地化字符串。
        /// </summary>
        public static string SkipUpdate {
            get {
                return ResourceManager.GetString("SkipUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speak Active Order 的本地化字符串。
        /// </summary>
        public static string Speak_Active_Order {
            get {
                return ResourceManager.GetString("Speak Active Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support 的本地化字符串。
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support Links 的本地化字符串。
        /// </summary>
        public static string SupportLinks {
            get {
                return ResourceManager.GetString("SupportLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The folder containing mod load orders 的本地化字符串。
        /// </summary>
        public static string The_folder_containing_mod_load_orders {
            get {
                return ResourceManager.GetString("The folder containing mod load orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The path to bg3.exe 的本地化字符串。
        /// </summary>
        public static string The_path_to_bg3_exe {
            get {
                return ResourceManager.GetString("The path to bg3.exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The path to the Data folder, for loading editor mods. 的本地化字符串。
        /// </summary>
        public static string The_path_to_the_Data_folder__for_loading_editor_mods_ {
            get {
                return ResourceManager.GetString("The path to the Data folder, for loading editor mods.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This enables features for mod developers, such as being able to copy a mod&apos;s UUID in context menus, and additional Script Extender options 的本地化字符串。
        /// </summary>
        public static string This_enables_features_for_mod_developers__such_as_being_able_to_copy_a_mod_s_UUID_in_context_menus__and_additional_Script_Extender_options {
            get {
                return ResourceManager.GetString("This enables features for mod developers, such as being able to copy a mod\'s UUID" +
                        " in context menus, and additional Script Extender options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Focus Filter for Current List 的本地化字符串。
        /// </summary>
        public static string Toggle_Focus_Filter_for_Current_List {
            get {
                return ResourceManager.GetString("Toggle Focus Filter for Current List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Light/Dark Mode 的本地化字符串。
        /// </summary>
        public static string Toggle_Light_Dark_Mode {
            get {
                return ResourceManager.GetString("Toggle Light/Dark Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Updates View 的本地化字符串。
        /// </summary>
        public static string Toggle_Updates_View {
            get {
                return ResourceManager.GetString("Toggle Updates View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Version Generator Window 的本地化字符串。
        /// </summary>
        public static string Toggle_Version_Generator_Window {
            get {
                return ResourceManager.GetString("Toggle Version Generator Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools 的本地化字符串。
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string TypeHeader {
            get {
                return ResourceManager.GetString("TypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updater 的本地化字符串。
        /// </summary>
        public static string Updater {
            get {
                return ResourceManager.GetString("Updater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updates: 的本地化字符串。
        /// </summary>
        public static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle the Mod Updates View 的本地化字符串。
        /// </summary>
        public static string UpdateViewToggleButtonTooltip {
            get {
                return ResourceManager.GetString("UpdateViewToggleButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version Generator 的本地化字符串。
        /// </summary>
        public static string VersionGenerator {
            get {
                return ResourceManager.GetString("VersionGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version Number: 的本地化字符串。
        /// </summary>
        public static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When launching the game, enable the Osiris story log (osiris.log) 的本地化字符串。
        /// </summary>
        public static string When_launching_the_game__enable_the_Osiris_story_log__osiris_log_ {
            get {
                return ResourceManager.GetString("When launching the game, enable the Osiris story log (osiris.log)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When moving selected mods to the opposite list with Enter, move focus to that list as well 的本地化字符串。
        /// </summary>
        public static string When_moving_selected_mods_to_the_opposite_list_with_Enter__move_focus_to_that_list_as_well {
            get {
                return ResourceManager.GetString("When moving selected mods to the opposite list with Enter, move focus to that lis" +
                        "t as well", resourceCulture);
            }
        }
    }
}
